# Background
background-color='#1e1e2e'

# Fonts
osd-font='JetBrainsMono Nerd Font'
osd-font-size=30
osd-color='#CDD6F4'
osd-border-color='#11111B'

sub-font='JetBrainsMono Nerd Font'
sub-font-size=40
sub-color='#F5E0DC'
sub-border-size=2

# OSD
osd-back-color='#11111b'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'

# Script opts
script-opts-append=stats-border_color=251818
script-opts-append=stats-font_color=f4d6cd
script-opts-append=stats-plot_bg_border_color=febeb4
script-opts-append=stats-plot_bg_color=251818
script-opts-append=stats-plot_color=febeb4
# script-opts=osc-boxalpha=0,osc-visibility=auto

# UOSC options
script-opts-append=uosc-color=foreground=b4befe,foreground_text=313244,background=1e1e2e,background_text=cdd6f4,curtain=181825,success=a6e3a1,error=f38ba8

# Misc
keep-open=yes
