# Includes
include=~/.config/fuzzel/colors.ini

# Size
horizontal-pad=20
vertical-pad=15
inner-pad=10

width=20

lines=10

# Text
font=GeistMono Nerd Font Mono:size=14
prompt="󰍉 "
placeholder=""

# Icons
icon-theme=yamis
icons-enabled=yes

# Others
[border]
width=2
radius=0

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
execute-or-next=Tab
