#!/usr/bin/env python3

from __future__ import annotations
import subprocess
from pathlib import Path
from typing import Callable
import notify2
import re

# Utils {{{


def spawn_fuzzel(options_string: str, prompt: str) -> str:
    executable = Path("/usr/bin/fuzzel")

    process = subprocess.run(
        [executable, "-d", "-p", prompt],
        input=options_string,
        capture_output=True,
        text=True,
    )
    process_output = process.stdout

    return process_output


def get_dunst_icon() -> str:
    executable = Path("/usr/bin/dunstctl")

    process = subprocess.run(
        [executable, "is-paused"],
        capture_output=True,
        text=True,
    )

    process_output = process.stdout.strip()

    if process_output == "true":
        return "󰂛"
    else:
        return "󰂚"


def spawn_popup_terminal(command: list[str]):
    local_command: list = ["kitty", "--class", "pop-up-terminal", "sh", "-c"] + command

    print(local_command)

    subprocess.run(local_command)


# }}}

# Classes {{{


class FuzzelOption:
    def __init__(
        self,
        title: str | Callable,
        command: list[str] | FuzzelMenu = [],
        return_back: bool = False,
    ) -> None:
        self._title = title
        self.command = command
        self.return_back = return_back

    @property
    def title(self) -> str:
        if callable(self._title):
            return self._title()
        return self._title

    def exec(self, menu: FuzzelMenu) -> FuzzelMenu | None:
        # Check if getting a command prompt
        if isinstance(self.command, list) and len(self.command) > 0:
            full_command = " ".join(self.command)

            subprocess.run(full_command, shell=True, capture_output=True, text=True)

            # Check if getting return_back is true
            if self.return_back:
                return menu

            return None

        # Check if getting a FuzzelMenu
        if isinstance(self.command, FuzzelMenu):
            return self.command

        return None


class FuzzelMenu:
    def __init__(
        self,
        options: list[FuzzelOption],
        prompt: str = "󰍜 ",
        has_back: bool = False,
        parent: FuzzelMenu | None = None,
    ) -> None:
        self.options = options
        self.prompt = prompt
        self.has_back = has_back
        self.parent = parent

    def show(self) -> FuzzelMenu | None:
        # Creating list copy with [:]
        local_options = self.options[:]
        if self.has_back and isinstance(self.parent, FuzzelMenu):
            local_options.insert(0, FuzzelOption(" Back", self.parent))

        # Formatting options for fuzzel
        formatted_options = "".join([f"{option.title}\n" for option in local_options])

        result = spawn_fuzzel(formatted_options, self.prompt).split("\n")[0]

        # Check if user pressed esc
        if not result:
            return None

        # Returning a selected option from local_option
        for option in local_options:
            if option.title == result:
                # Check if return_back is true
                return option.exec(self)

        return None


# }}}

# Configuration {{{


def setup_menus():
    popup_terminal = ["kitty", "--class", "pop-up-terminal", "sh", "-c"]

    main = FuzzelMenu(options=[])
    power = FuzzelMenu(options=[], prompt="󰐥 ", has_back=True, parent=main)

    main.options = [
        FuzzelOption("󰣇 System"),
        FuzzelOption("  󰐥 Power Menu", power),
        # TODO make this, note in Obsidian
        FuzzelOption("  󰚰 Update", ["echo", "done"]),
        FuzzelOption(
            lambda: f"  {get_dunst_icon()} DND",
            ["dunstctl", "set-paused", "toggle"],
            return_back=True,
        ),
        FuzzelOption("  󰖩 Network", popup_terminal + ["nmtui"]),
        FuzzelOption(" Configs"),
        FuzzelOption("   Open ~/.dotfiles", ["$FILE_MANAGER", "~/.dotfiles/"]),
        FuzzelOption(
            "  󰏫 Edit Kitty",
            ["$FILE_MANAGER", str(Path.home() / ".dotfiles/kitti/.config/kitty/")],
        ),
        FuzzelOption(
            "  󰏫 Edit Niri",
            ["$FILE_MANAGER", str(Path.home() / ".dotfiles/niri/.config/niri/")],
        ),
        FuzzelOption(
            "  󰏫 Edit Waybar",
            ["$FILE_MANAGER", str(Path.home() / ".dotfiles/waybar/.config/waybar/")],
        ),
        FuzzelOption(
            "  󰏫 Edit yazi",
            ["$FILE_MANAGER", str(Path.home() / ".dotfiles/yazi/.config/yazi/")],
        ),
        FuzzelOption(
            "  󰏫 Edit zsh",
            ["$FILE_MANAGER", str(Path.home() / ".dotfiles/zsh/.config/zsh/")],
        ),
    ]

    power.options = [
        FuzzelOption("  󰐥 Shutdown", ["systemctl", "poweroff"]),
        FuzzelOption("   Reboot", ["systemctl", "reboot"]),
        FuzzelOption("   BIOS Setup", ["systemctl", "reboot", "--firmware-setup"]),
    ]

    return main


# }}}

if __name__ == "__main__":
    current = setup_menus()
    while current:
        current = current.show()
