[mgr]
prepend_keymap = [
    # Jumps
	{ on = ["g", "d"], run = "cd ~/downloads", desc = "Go ~/downloads" },

	# Smart-enter
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	{ on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

    # Disk mounting
    { on = "M", run = "plugin mount", desc = "Open mount menu" },
]
