[mgr]
prepend_keymap = [
    # Jumps
	{ on = ["g", "d"], run = "cd ~/downloads", desc = "Go ~/downloads" },
	{ on = ["g", "t"], run = "cd ~/.dotfiles", desc = "Go ~/.dotfiles" },
	{ on = ["g", "p"], run = "cd ~/media/pics", desc = "Go ~/media/pics" },
	{ on = ["g", "v"], run = "cd ~/media/vids", desc = "Go ~/media/vids" },

	# Smart-enter
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	{ on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

    # Disk mounting
    { on = "M", run = "plugin mount", desc = "Open mount menu" },

    # Relative motions
    { on = "1", run = "plugin relative-motions 1", desc = "Move in relative motion steps"},
    { on = "2", run = "plugin relative-motions 2", desc = "Move in relative motion steps"},
    { on = "3", run = "plugin relative-motions 3", desc = "Move in relative motion steps"},
    { on = "4", run = "plugin relative-motions 4", desc = "Move in relative motion steps"},
    { on = "5", run = "plugin relative-motions 5", desc = "Move in relative motion steps"},
    { on = "6", run = "plugin relative-motions 6", desc = "Move in relative motion steps"},
    { on = "7", run = "plugin relative-motions 7", desc = "Move in relative motion steps"},
    { on = "8", run = "plugin relative-motions 8", desc = "Move in relative motion steps"},
    { on = "9", run = "plugin relative-motions 9", desc = "Move in relative motion steps"},
]
